### ISSUE TITLE
Can't execute any theme options

### ISSUE THREAD

**Issue by maicol07** [TheOld/vscode-fluent-ui#28] opened 2022-07-14 16:51 UTC
Hi,
when I try to execute an option from the theme (enable, disable or reload) I get this error:
```
 (ENOENT: no such file or directory, open 'c:\Users\Maicol\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-browser\workbench\workbench.html'))
```
Can you fix it?
Thanks

**Comment by MrStanDu33** [comment] 2022-07-20 11:32
Same here, workbench folder seems to be located in

`WhereverVsCodeIsInstalled\resources\app\out\vs\code\electron-sandbox\workbench\workbench.html`
not
`WhereverVsCodeIsInstalled\resources\app\out\vs\code\electron-browser\workbench\workbench.html`

I think it is due to our insiders build that might have a different file structure, as I cannot reproduce the bug in the latest non-insiders Visual Studio Code version.

@maicol07 If you really want (until this issue is fixed) to enable Fluent UI, here are the steps :

 1. Copy the `workbench` folder present in `electron-sandbox` into `electron-browser`
 2. Run Visual Studio Code as admin and execute *~~order 66~~* `Fluent Ui: Enable` command in command palette
 3. Close Visual Studio Code
 4. Backup `workbench` folder present in `electron-sandbox` (by renaming it `workbench-old`)
 5. Copy the `workbench` folder present in `electron-browser` into `electron-sandbox`
 6. Reopen Visual Studio Code, and voilà 🎉

**Comment by txyyh** [comment] 2022-08-05 16:15
VSCode version 1.70.0 stable reproduced

**Comment by TheOld** [comment] 2022-10-10 01:31
Hey all. I'm sorry I haven't been anywhere near this project this year, a lot going on 😐.
Anyways, I merged [this PR](https://github.com/TheOld/vscode-fluent-ui/pull/31) today with a fix for the issue and a new release is out. So `2.1.0` should be working on the newer versions of VSCode.

**Closed** 2022-10-10 01:32 UTC
